### ISSUE TITLE
Uncaught (in promise): Error: Loading chunk XY failed

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/cordova-plugin-ionic-webview#118]
# Bug Report

**Describe the Bug**

When we monitor our apps with Sentry, we often get reports of the following error:

> ERROR Error: Uncaught (in promise): Error: Loading chunk 34 failed.
> n@http://localhost:8080/var/containers/Bundle/Application/9461767B-/MyApp.app/www/build/vendor.js:1:561
> H@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/polyfills.js:3:23955
> r@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/vendor.js:1:920809
> runTask@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/polyfills.js:3:10844
> invokeTask@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/polyfills.js:3:16801
> p@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/polyfills.js:2:27654
> v@http://localhost:8080/var/containers/Bundle/Application/9461767B/MyApp.app/www/build/polyfills.js:2:27894

Some people get "Error: Loading chunk 34 failed" or "...20 failed" or "....0 failed

After discussing the problem on the Ionic forum, we could figure out that we were a couple of Ionites facing the same issues and that we were all facing it in the following situation:

- We are all using lazy loading
- We are all seeing the report in Sentry
- We are all noticing the issue only at boot time of our apps
- We are all facing the issue only on iOS

Since we are all facing the issue only on iOS, I thought the problem might be related to the cordova-plugin-ionic-webview plugin

**Resource**

https://forum.ionicframework.com/t/uncaught-in-promise-error-loading-chunk-20-failed

**Version**

cordova-plugin-ionic-webview: 1.2.1
ionic-angular: 3.9.2
node: 10.2.1

**Unfortunately no demo repo**

I'm really very sorry that I can't provide a sample repo, it's not that I don't want to, it's just that it's super difficult to reproduce the error outside production, I wasn't able to reproduce the error when developing

**Side note**

If you want to access to my Sentry account to get more information, if that could help, no worries let me know

**Side side note**

I google the error "webpack Loading chunk failed" and if I understood it look like the error might occurs when updating apps and chunks name change or something...I may be completely wrong but if that could help...

**Comment by sebaferreras** [comment]
I'm getting this error as well, after releasing an app update through the app store. 

> - We are all using lazy loading
> - We are all seeing the report in Sentry
> - We are all noticing the issue only at boot time of our apps
> - We are all facing the issue only on iOS

We actually use _Raygun_ for error reporting, but the other items are 100% the same on our end.

> I'm really very sorry that I can't provide a sample repo, it's not that I don't want to, it's just that it's super difficult to reproduce the error outside production, I wasn't able to reproduce the error when developing

I've been trying to reproduce this issue installing updates via XCode hundreds of times, but I couldn't reproduce it not even once that way. It only happens with the app being updated via the App Store.

**Comment by cmartin81** [comment]
I'm also getting this error. My app is facing this problem at IOS boot time and I'm using lazy loading

**Comment by jh-gh** [comment]
We are also getting this error on iOS startup (reported through Fabric).  We have mostly seen this in production builds.  However, just yesterday it occurred with one of our debug builds installed through TestFairy.

**Comment by peterpeterparker** [comment]
Most probably the problem isn't related to cordova-plugin-ionic-webview but to webpack, therefore I close my issue  https://forum.ionicframework.com/t/uncaught-in-promise-error-loading-chunk-20-failed/126937/47?u=reedrichards

**Comment by joewoodhouse** [comment]
I'm also seeing this issue, not really sure why this issue was closed (even if it is related to webpack, it's still an Ionic issue?). This plugin seems pretty unusable at the moment with all the issues.

**Comment by peterpeterparker** [comment]
@joewoodhouse if it's webpack related, there won't be any update in app-script, I guess, since Ionic v4 is based on the Angular Cli

So this would be only solve when webpack would be updated (or maybe it's already the case I don't know) and in Ionic v4

that's why I closed the issue

but the topics on the forum is more active

**Comment by joewoodhouse** [comment]
Ok. But there's plenty of people (like me) supporting apps that are commercially available that aren't on Ionic v4 (as it only went beta yesterday). I don't think we can stop fixing ionicv3 issues just yet, especially when it completely stops the app working.

**Comment by peterpeterparker** [comment]
@joewoodhouse first of all, that's only my guess, I'm not part of the Ionic team, I've no more information than you

then there is an issue in app-script to update webpack, that's maybe the issue you want to follow https://github.com/ionic-team/ionic-app-scripts/issues/1403

but again, if we assume that the error is linked to webpack, it might not be

finally, if it's a must, as always, everything is open source, you could give a try ;)

**Comment by kirillgroshkov** [comment]
We also have same error. And in the original discussion seems like there are quite a lot of people struggling to find a solution: https://forum.ionicframework.com/t/uncaught-in-promise-error-loading-chunk-20-failed

I see 0 proof that it's webpack related. Correct me if I'm wrong.

I see 0 chance that Ionic v3 will update webpack to 4 (since it's abandoned in favor of ionic v4).

But... we need solution! We have users! Help us!

**Comment by TLMNicolas** [comment]
We too have this issue on 2.2.x of the plugin.
We were at 1.1.16 and decided to update to try some fixes associated with the newer keyboard plugin - which required the newer 2.2.x plugin.
Well 2.2.x definitely has some problem. 

I looked into it and the problem is because the app code tries to load the chunk (a js file named XX.js) and the built in webserver doesnt serve it. I checked the compiled IPA file and the .js file is there, so why is the web server not serving the file? I dont know.

In the end we went back to 1.1.16

**Comment by jwburnside** [comment]
Having the same issue with very similar specs as the original poster.

Seems like no one has a solution for this in my research. Does anyone know of a way to at least catch the webpack error?

**../../webpack/bootstrap f9f6d79602cb7bf2af52:103onScriptComplete**
```
var chunk = installedChunks[chunkId];
if(chunk !== 0) {
   if(chunk) {
     chunk[1](new Error('Loading chunk ' + chunkId + ' failed.'));
   }
    installedChunks[chunkId] = undefined;
}
```

**Comment by jh-gh** [comment]
We have seen a couple of reports of this a day from our production apps (through Fabric) ever since we went live with our app more than a year ago.  Up until recently, this never seemed to occur on our test devices ... only on real user's devices.  However, we have recently started to encounter this on test devices as well.  I suspect that what has changed is that we are developing a second app using the same ionic-webview plugin (1.2.1) and running both apps on the same device.  That plugin uses an internal web server (on ios) running on port 8080.  It seems like under some circumstances ... the apps interfere with each other.  So, when one app tries to lazily load some resource from the web server ... it may fail ... because the other app has taken over 8080.  I can't seem to make this happen easily on purpose ... usually both apps work fine.  But sometimes one of them fails.

So, now I suspect that the reason for the production crashes may be that occasionally we run into a customer that has our app ... and another app from who knows where that also uses this plugin trying to use port 8080.

Does this sound right?

Any suggestion for the best approach to avoid this problem (Ionic V3)?  I am extremely loath to upgrade to a newer version of the ionic-webview plugin as 1.2.1 seems to be adequate for our needs and both the 2.X and 4.X versions seem to have a very high level of activity/issues etc.  But would love to hear any thoughts on this.

**Comment by richardshergold** [comment]
Did anyone find a solution to this?  We are seeing several thousand of these events a week on Sentry.

**Comment by jh-gh** [comment]
We ended up moving to the 2.X webview plugin for iOS which allows us to specify a specific port to listen on.  Of course this is not ideal either as there is no guarantee that you can choose a port that won't clash with something else ... but at least you can avoid running on 8080 which has the highest chance of collision.

**Comment by ulesta** [comment]
Hey @jh-gh running into the same problem here. You mentioned you switched over to 2.X and specified a port, I'm guessing two different ports for the two different apps. I'm wondering whether you ran into the issue again or if you think that had solved it! Let me know! Thank you! 🙏

**Comment by jh-gh** [comment]
Unfortunately running each of our apps on different ports has not completely eliminated this problem in production.  We still see occasional "Loading chunk error" reports from production.  I suppose it's possible in theory there is yet another app that is trying to use the ports we have allocated.  The crashes are fairly infrequent but still quite frustrating and I find it surprising that more people don't seem to report this as an ongoing problem.

**Comment by ulesta** [comment]
Hey @jh-gh I see, thanks for elaborating! I tried to replicate this by pushing two apps that use the exact same port, but I'm afraid I don't get the ChunkLoadError, but what happens instead is this: if you open the another app that listens to the same WKWebView port right after putting the current app into the background, the app fails to load entirely with a blank page saying "Unable to load app"

At this point, I'm starting to think that ChunkLoadError might be another issue not related to using the same port at all. But I'd love to hear your thoughts on it. Were you able to verify that running two apps with the same ports actually produces a ChunkLoadError?

Thanks for you help! Trying to debug this is like trying to find a need in the haystack 😓

**Comment by jh-gh** [comment]
Hey @ulesta, yes I had trouble debugging it and I am not really a native ios dev.  Pretty sure it is related to the port though.  From memory, I was able to make it fail consistently if I started 2 different apps using the same port from XCode (or maybe even just one of them from XCode).  Not sure why running from XCode matters but it did.  If I run them normally then it very very rarely fails with the chunk error (bit it still does occasionally as I can tell from my log reports).

**Comment by ulesta** [comment]
Hi @jh-gh thanks for sharing those details! It's a little strange because I can never seem to emit the ChunkLoadError when two apps are sharing the same port. Nonetheless, thanks again, I really appreciate it! I'll keep you posted on my end! 😃

**Comment by nvahalik** [comment]
We have this problem too. Of course, we've changed our port away from 8080 months ago due to similar issues. A very small number of users report this issue, but they are very vocal about it. I'm trying to get an idea of what's going on but again, it's very hard to get any sort of information about this.

What would be helpful is if there was some way to report from the underlying app. I'm curious if anyone in this thread has tried Rollbar or error reporting for Firebase? That runs at at the app level rather than the view level?

**Comment by machty** [comment]
We're also seeing sporadic reports of this on prod (via Bugsnag). A few thoughts to offer:

- Yes, there is a possibility of another app listening on port 8080, which will completely prevent your app from loading unless you change the port; in this case, it wouldn't even be able to load index.html, and hence it can't be the cause of "chunk N failed to load" errors
- Unless some other app is holding port 8080 while it's in the background, it's actually pretty difficult to reproduce a "port-8080-in-use" error, because the HTTP server that this plugin spins up is automatically set to suspend in the background; in most cases, this'll make it difficult to reproduce this error when testing your own ionic apps, since in most cases the first app will teardown its HTTP server when it goes into the background before your new app can load. Hence, I was only able to replicate this kind of error by launching an app from XCode directly (rather than homescreen) while another app was already running; in this case, the first app didn't even have enough time to teardown the HTTP server. This sounds like what @jh-gh was seeing.
- So, while it's a good idea to change your webview port to something random to avoid a collision with some random other app using 8080, I don't believe it'll have any impact on these sporadic "chunk N" loading failure errors because in these cases you wouldn't even be able to load index.html

So, I am still at a loss for what's causing these random issues on prod. Maybe there's an underlying issue with the GCD server very occasionally failing to serve the chunk js file?
