### ISSUE TITLE
[Android] v2+ breaks compatibility with API 19 (probably others)

### ISSUE THREAD

**Issue by chancezeus** [ionic-team/cordova-plugin-ionic-webview#149]
The current v2 implementation breaks compatibility with API 19 (as shown in attached screenshot).

![screenshot_1534963062](https://user-images.githubusercontent.com/2089196/44483573-c1dc5300-a64b-11e8-8db3-88b1d8f7d2b6.png)

It can easily be reproduced by running (any) app on a API19 VM. I think this is related to the (quite major) difference between the webview on older android devices and the more recent ones. As with iOS I however do expect the plugin to work on all supported platforms (which is API 19+ on cordova-android 7.1.1).

**Comment by KevRyan2** [comment]
can you post your config.xml and any other info you might think would be useful?  and were you trying to run this with live reload or a build at the time you took this screenshot?

**Comment by chancezeus** [comment]
The running build is a release build and it is a regression from 1.x since there it did work, I've attached a plain ionic (tutorial template) project which you can run against API 19 (in the emulator) and it is still broken so it is an issue with this plugin and not plugin interaction.

[webview-v2-broken.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/2313362/webview-v2-broken.zip)

**Comment by lucasbasquerotto** [comment]
@chancezeus In the main page of this repo (https://github.com/ionic-team/cordova-plugin-ionic-webview) you can see that the new version of this plugin (2+) supports only Android 5+, while the API 19 is related to Android 4.4.

This seems due to the change from serving in `http://localhost:8080/` instead of `file:///`

I can't say for sure if this choice was for the best or not (Android 4 is kind of old, but still has some significant amount of users using it), but if you want it to work in Android 4 you should use version 1.2.1.

There are lots of issues regarding that in the forum:

https://forum.ionicframework.com/search?q=localhost%3A8080%20order%3Alatest

From what I see, the solution is downgrading the version of this plugin.

**Comment by chancezeus** [comment]
In that case the plugin.xml should also specify the correct minSdk and I think it would be highly preferable if pre-5.x users fall back to the regular (cordova) webview instead of killing it like this (like the iOS plugin does).

**Comment by janpio** [comment]
If you need a way to get this working again, you (currently) will probably have to downgrade back to 1.x of the plugin. I wrote a bit about this problem: https://ionic.zone/debug/ionic-and-android-4#downgrade

**Comment by silaslira** [comment]
Looking forward for [`this pull request`](https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/144) getting merged.

**Comment by jcesarmobile** [comment]
The part of that PR that added the sdk 19 support has been merged, will be included in next release
