### ISSUE TITLE
Cannot access local files with inappbrowser on Android

### ISSUE THREAD

**Issue by pauldunn** [ionic-team/cordova-plugin-ionic-webview#178]
I have a html file in my www folder called test.html.

I am trying to use the inappbrowser to open this file but I get this error on Android:
err::ERR_CONNECTION_REFUSED

IOS opens the file as expected.

Screenshot:
![screen shot 2018-09-26 at 13 33 09](https://user-images.githubusercontent.com/483640/46080157-0d28da80-c191-11e8-938d-515ac83847d9.png)

What I am trying to do is host a mini static website in the www folder so I can open this from my Ionic app with the inappbrowser.

Is it possible to do this?

**Comment by herbertbruno** [comment]
same problem.

**Comment by jcesarmobile** [comment]
You'll need cordova-plugin-file to get the file system path, the localhost paths are only accesible in the Ionic WebView, but not in InAppBrowser

**Comment by herbertbruno** [comment]
works fine. 
this.file.applicationDirectory + 'www/assets/foldername/index.html

Thanks

**Comment by herbertbruno** [comment]
That works. But we use localStorage to send back some data from InAppBrowser. 
Since the URLs are different we face the cross domain localStorage problem,
From the app unable to access the localStorage that are set  from InAppBrowser.

**Comment by jcesarmobile** [comment]
Why do you open them in InAppBrowser instead of opening them inside the own webview? InAppBrowser was created to open external websites.

Anyway, next release of InAppBrowser will include postMessage, so you'll be able to communicate without localStorage "hacks" https://github.com/apache/cordova-plugin-inappbrowser/pull/362.
And also current version provides executeScript that can be used to obtain the current localStorage

**Comment by herbertbruno** [comment]
we also use other UI frameworks instead of ionic, so to avoid conflicts we use IAB.
However I have tried the **"postMessage"** and it works.
Thanks,
