### ISSUE TITLE
Can we resolve CORS issue of WKWebView from front-end.

### ISSUE THREAD

**Issue by mayurala** [ionic-team/cordova-plugin-ionic-webview#225]
Can I resolve the CORS issue of WKWebView from the front-end without using the Ionic Native Http Plugin? I have tried CSP and whitelist plugin to resolve it but seems that it's not working. I have tried all the way through CSP (https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/security/whitelists?view=toolsforcordova-2017 ) but it's not working. With Ionic Native HTTP, I have to replace my angular HTTP which might have side effects in my project architecture. Ionic Native HTTP is not working with RXjs. Please help.

**Comment by kensodemann** [comment]
In most cases CORS issues are caused by the server that supplies our data not handling CORS correctly (or at least correctly for your application, though it could be handling it correctly for another web application that is getting the data, etc.)

Here is some good information on what is needed: https://ionicframework.com/docs/wkwebview/#cors

**Comment by troyanskiy** [comment]
Please check that https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/227

**Comment by aftabdess** [comment]
Enabling CORS makes the application vulnerable. Isn't there any other alternative ?
