### ISSUE TITLE
[v3] Error using ionic-native/geolocation (Unsecure origin)

### ISSUE THREAD

**Issue by Jaimegon** [ionic-team/cordova-plugin-ionic-webview#259]
Hello everyone,
I upgraded to 3.0.0 as recommended by the Ionic team. When trying to use the plugin ionic-native/geolocation it says: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."
The reason seems to be that I am using HTTP instead of HTTPS. In https://goo.gl/Y0ZkNV says HTTP is permited with localhost, but I change my server name for seacurity reasons with:

`<preference name="Hostname" value="newName" />`

And, for Android, I allowed the navigation with the new name:

`<allow-navigation href="http://newName/*" />`

Is there any workaround? Can I simulate the request from a secure origin (HTTPS)?

**Info:**
OS: Android, not checked in iOS
ionic-angular 3.9.2
@ionic-native/geolocation": "^4.19.0"
cordova-plugin-ionic-webview 3.0.0

**Command:**
ionic cordova run android

If you need more information, don't hesitate to ask for it.
Thank you very much

**Comment by jcesarmobile** [comment]
There are no security reasons to change localhost to another value, it's not a real web server, localhost is only accesible to your app.

If you change the Hostname then you won't be able to use some features like geolocation

**Comment by jcesarmobile** [comment]
CORS only prevents websites from accessing resources from other domains when using XHR/fetch, when building apps (native/Cordova/Capacitor) you shouldn't worry about it, but sadly in Cordova/Capacitor apps you need to worry because as they are based in web technologies, they have some of it's limitations.

By configuring CORS you are not protecting the web server, anybody can do a GET or POST request to it using CURL, postman, a native connection, a web server (proxy) and another hundred ways, it just prevents XHR and fetch and an attacker won't be using XHR or fetch.

**Comment by shivarajnaidu** [comment]
There are 100 ways but atleast i can set custom CORS domain name in my server (The API's also consumed by my website) instead of * .. changing the host name will be helpful .  I think this is good to have feature to set custom hostname but unfortunately my native plugins failing when i change the hostname. @jcesarmobile
