### ISSUE TITLE
Cookies are not set/stored in iOS 

### ISSUE THREAD

**Issue by FarhadG** [ionic-team/cordova-plugin-ionic-webview#300]
Since we upgraded from the old `UIWebView` engine, we are not able to authenticate our users (using an external auth service), as none of the cookies sent by the APIs are being set in the this web view. 

This is a major blocker for us and have been trying to determine what a good course of action is. If our assumptions are correct that cookies are not supported with this web view (which is very strange), we are going to try:

- Proxy (not sure if you recommend a good plugin for this)
- Native fetch (not sure if you recommend a good plugin for this)

Our stack:
- Cordova
- React
- Fetch for calls

**Comment by aecvargas** [comment]
I'm also experiencing the same issue.

**Comment by FarhadG** [comment]
Yeah, this has been driving us crazy over the past couple of weeks, @aecvargas

**Comment by gabriele-bjss** [comment]
Same issue here. I installed this plugin in my Cordova project and cookies work fine on Android but not on iOS! :(

**Comment by aecvargas** [comment]
@FarhadG @gabriele-bjss 

I don't know if you guys have seen the potential solution found in this article:
https://novemberfive.co/blog/WKWebView-redirect-with-cookies

But I'm not entirely sure how to apply this fix to my ionic/cordova app as it is all in .swift and I am not familiar with swift at all.

**Comment by mesju** [comment]
Same issue here. Would be nice it will be fixed.

**Comment by jcesarmobile** [comment]
I can get them to work, but just after killing the app as on https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22, so going to close as duplicate.

Make sure you have `xhr.withCredentials = true;` if using XHR or `credentials: 'include'` if using fetch. That's required for cookie credentials to work on WKWebView while it wasn't on UIWebView.

They can also work if you set `<preference name="Hostname" value="" />` to match the host where you are making the calls to, but it's not really a good solution as might break the Android app unless you change the scheme to not match your server one. (I.E. if you call to `https://yourserver.com/file.json` and you have `<preference name="Hostname" value="yourserver.com" />` and `<preference name="Scheme" value="https" />` it will be intercepted and look for a local file instead of for the remote one, if you set the scheme to http or ionic it will work, but might have some other problems.

**Comment by aecvargas** [comment]
@jcesarmobile I've got this all set up which is why it works for my Android version. It does work for the iOS but once the app has been ran once but it shouldn't have to work like that. It is still an issue for iOS on WKWebView. 

From what I have gathered upon researching this is that this issue has been around for at least a couple of years now and Apple has not added a fix for it and I don't think there will be any fixes either. Some people have created cordova/ionic plugins to allow the cookies to work for WKWebView but this only works for iOS 11+ I believe. An alternative is to this is to switch back to UIWebView which isn't really ideal but it does work.

**Comment by jcesarmobile** [comment]
I’ve closed it because there is another issue open (#22)

**Comment by lucky3491** [comment]
this plugin is working for me [https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie](https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie)

**Comment by juliannehalversen** [comment]
> this plugin is working for me https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie

I am building an app with Ionic and Angular and would like to use your plugin but am having issues. When I install the plugin and try to import it, it's not available to use. Is there something I'm missing here?
<img width="524" alt="Screen Shot 2020-05-05 at 1 54 27 PM" src="https://user-images.githubusercontent.com/42973566/81109943-1b47ec80-8ed8-11ea-8308-c414f72fcab2.png">

**Comment by rsgone** [comment]
@juliannehalversen simply declare a normal variable as follows:

`declare var wkWebView: any;`

**Comment by dmitrytemlead** [comment]
Are there any updates?

**Comment by juliannehalversen** [comment]
> Are there any updates?

Here is the link to what I did to fix it: https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie/issues/1#issuecomment-633614645

**Comment by rafaellop** [comment]
This worked https://github.com/CWBudde/cordova-plugin-wkwebview-inject-cookie/issues/11#issuecomment-883249020
