### ISSUE TITLE
Plugin fails to be added with cordova-cli 9

### ISSUE THREAD

**Issue by ilyakamens** [ionic-team/cordova-plugin-ionic-webview#340]
```
$ cordova --version
9.0.0
```

```
<plugin name="cordova-plugin-ionic-webview" spec="https://github.com/ionic-team/cordova-plugin-ionic-webview.git">
    <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
</plugin>
```

```
$ cordova platforms
Installed platforms:
  android 8.0.0
  ios 5.0.0
```

Error message: `Failed to restore plugin "cordova-plugin-ionic-webview" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Looks like `requireCordovaModule` is gone.

**Comment by jcesarmobile** [comment]
Despite the error message points to this plugin, it's actually another one using `requireCordovaModule` and not us.

Also cordova 9.0.0 seems to have problems on restoring plugins, should be fixed in next 9.0.1 release.

**Comment by ilyakamens** [comment]
@jcesarmobile - thanks for the prompt response.

Can you elaborate? The error message seems to indicate pretty clearly that `cordova-plugin-ionic-webview` uses `requireCordovaModule`. I've seen in other plugins that one of their dependencies used `requireCordovaModule`, but cordova still blamed the plugin itself. Is that what you mean or?

Thanks again!

**Comment by jcesarmobile** [comment]
Cordova error logging is not very good at this kind of errors, the first one is cordova-plugin-ionic-webview not being able to be restored, that's because of the cordova 9.0.0 restoring issue. See https://github.com/apache/cordova-lib/pull/752, it's fixed, but not released yet, will take at least 3 more days as that's for cordova-lib, which is about to be released today, then a cordova-cli release must follow up in 2-3 days.

Then the `requireCordovaModule` is for another plugin, usually the next one that it tries to install/restore. Check for plugins with hooks are usually the ones using `requireCordovaModule`.
You can check this plugin source code and you won't find the `requireCordovaModule` anywhere.

**Comment by ilyakamens** [comment]
You're right--sorry for the noise @jcesarmobile!
