### ISSUE TITLE
ITMS-90809: Deprecated API Usage  ionic 5

### ISSUE THREAD

**Issue by uldcra** [ionic-team/cordova-plugin-ionic-webview#436]
Hello everybody.
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview.

My english is very poor.
But I don´t know hot to solve this issue in Ionic 5.

**Comment by ldezho** [comment]
I also encountered the same problem

**Comment by ldezho** [comment]
#431

**Comment by jcesarmobile** [comment]
As Idezho said, see https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/431

But, it's a warning, so you shouldn't worry for now.
The only final solution for now is moving your app to Capacitor
If you want to continue using cordova, there are two cordova-ios forks with two different approaches that you can use instead of the original.
