### ISSUE TITLE
[Process] kill() returned unexpected error 1

### ISSUE THREAD

**Issue by desmeit** [ionic-team/cordova-plugin-ionic-webview#471]
With IOS 13.2 and Xcode 11.2 I get the following error.

`[Process] kill() returned unexpected error 1`

 it’s logging every 10ms.

Is there a solution?

**Comment by SevenSystems** [comment]
There's apparently a way to disable the logs, see the bottom of this page:

https://stackoverflow.com/questions/58321114/why-i-get-the-console-warning-process-kill-returned-unexpected-error-1-when

Unfortunately, this apparently will never get fixed as it is still present in iOS 13.2.2. It's also creating massive CPU and battery drain, though I'm not sure if it's only while running in XCode, or also in the App Store version.

A massive problem for sure.

**Comment by atuaimi** [comment]
Will never get fixed? How did you come up with that?

Indeed a massive problem and I am wondering why it is not getting much attention and a rapid fix! Many has reported that this problem is present in both XCode and downloaded apps. Also, some reported that this problem is crashing their apps no matter what. Honestly, I started now questioning the reliability of developing native apps on top of ionic/cordova/capacitor.

**Comment by stewwan** [comment]
same

**Comment by dotNetkow** [comment]
This isn't an Ionic bug, but rather a [WebKit one](https://bugs.webkit.org/show_bug.cgi?id=202173). Unfortunately, not much to do until Apple deploys a fix in a future version of iOS.

**Comment by ajjing** [comment]
Same problem, who can give a solution?

**Comment by rileynetadmin** [comment]
Same problem. Just fills up my logs.

**Comment by YanjiangWu** [comment]
无情，还搞个鸡毛？

**Comment by jcesarmobile** [comment]
it's fixed on iOS 13.4
