### ISSUE TITLE
Unable to get WKWebview working with native Photo Library plugin

### ISSUE THREAD

**Issue by jaybloke** [ionic-team/cordova-plugin-ionic-webview#54]
When using WKWebview, custom schemes like cdvphotolibrary:// do not appear to work (even with dom sanitiser in place).

The cdvphotolibrary:// scheme is employed to show thumbnails etc when filtering photos from the cordova photo library plugin.

Had to revert back to UIWebView in order to get the photo library plugin to work.

Issue also mentioned here: https://github.com/terikon/cordova-plugin-photo-library/issues/41

**Comment by Sh1d0w** [comment]
@manucorporat This is a serious issue that stops a lot of developers to use the plugin. Any thoughts on this so far?

**Comment by mhartington** [comment]
This make sense, since the wkwebview plugin uses a file server to serve the app contents. 

http://ionicframework.com/docs/wkwebview/

We mention this in the WKWebview docs, but you cannot use any file protocol when referencing native files. This also includes the `cdvfile://` protocol. Instead, get the full file path, and use the `normalizeUrl` function.

https://ionicframework.com/docs/wkwebview/#rewriting-file

**Comment by v-ken** [comment]
@mhartington 
When using FILE_URI destination type, the EXIF data seems to be missing. It is however available when you use NATIVE_URI type, but this results in a cdvfile:// format which doesn't work with WKWebView. Is there anyway to obtain a file type on the local server AND all EXIF data related to a photo?
