### ISSUE TITLE
cordova-ios@6.0.0 is release

### ISSUE THREAD

**Issue by boboxiaodd** [ionic-team/cordova-plugin-ionic-webview#582]
What is the difference between the cordova-ios@6.0.0 and cordova-plugin-ionic-webview ?

**Comment by jcesarmobile** [comment]
I guess you mean the webview that cordova-ios 6 includes vs the webview cordova-plugin-ionic-webview uses.

At the moment both of them use WKWebView.
Main differences are:
- the webview on cordova-ios allows to load from file: protocol or load from custom schemes, while ionic-webview only allows custom schemes.
- ionic-webview has some code to make ionic appflow work (live deploys)
- ionic-webview has some code to allow autofocus/js focus on input fields on ios

other than that they are mostly the same

you can still use cordova-plugin-ionic-webview if using cordova-ios 6 since cordova-ios allows to use custom webviews.

**Comment by brassier** [comment]
This is very helpful.  Would it be possible to put a note like this in the plugin docs?
