### ISSUE TITLE
if 2 or more ionic app running with same port then it create issue for ios

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/cordova-plugin-ionic-webview#91]
Hello 

here is my ionic info 

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Program Files\Android\android-sdk

Misc:

    backend : pro

and i have build ios using phonegap build 
my main issue is 
in ios this plugin create local serve and default port is 8080 
now if another ionic app which has same type port then it will conflict and break app .

**Comment by revie** [comment]
I used to think the same thing, that everyone sharing the same port would likely encounter conflicts.  So, when I was working on implementing this into my projects last year, I ran quite a few tests, both on simulators and on real devices, to try to get port 8080 conflicts.  I even resorted to running apps side-by-side like you can on iPads to visually see both apps running at the exact same time.

Never once was I able to get things to break.  I haven't spent the time to track down the reason, but my gut says that it's likely due to Apple's sandboxing, making it impossible for one app to affect another.  I know in theory things should break, but it doesn't seem to work out that way, at least for me.

If you're seeing conflicts somehow, do you mind sharing how you are able to encounter the issue?  The latest version of this plugin makes the port configurable, so it's probably moot anyways, but I'd love to finally see a way to get it to break.

**Comment by ipehimanshu** [comment]
for me as practically as i have checked 
some time when menu shows active in one app wrong 
and if click footer menu for one app then it goes to wrong page don't know how but that is truth .

So if i have changed both apps port then it working fine.

**Comment by revie** [comment]
I've tried it with a number of different combinations and can't get it to break.  Strange.  I am testing with apps that are similar, having similar routing, though very different content pages.  In theory I should be seeing different content, like how you're seeing different routing.  Maybe I'm missing something.

Are there maybe other Cordova plugins you may be using that could be assisting WebView in breaking the iOS sandbox and affecting other apps?  Do you mind posting your list of plugins?

**Comment by joewoodhouse** [comment]
We are also seeing the same issue.

**Comment by sathishTkumar** [comment]
+1

**Comment by bharathiselvan** [comment]
+1
Me too  face the same problem.

**Comment by mlynch** [comment]
This is fixed as of 2.2.0. See also #165
